# The URL the site will be built for
base_url = "https://log.robi42.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Robi's Blog"
description = "On Life, the Universe and Everything, but mainly Software Development"
author = "Robert Thurnher"

theme = "hyde"
generate_feeds = true
#taxonomies = [{name = "tags"}]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[markdown.highlighting]
# Syntax highlighting for code blocks (Zola 0.22+ syntax);
# theme can be set to any theme supported by Zola
style = "inline"
theme = "nord"

[extra]
# Put all your custom variables here
hyde_theme = "theme-base-0e"
#hyde_reverse = true
hyde_links = [
    {url = "/about", name = "About"},
]

